# Generated by Django 5.2.12 on 2026-05-23 14:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(help_text='Roblox Username', max_length=100, unique=True)),
                ('roblox_id', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Farming', 'Farming'), ('Sniping', 'Sniping'), ('Idle', 'Idle'), ('Dead', 'Dead'), ('Offline', 'Offline')], default='Offline', max_length=20)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('level', models.IntegerField(default=1)),
                ('money', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('session_time', models.IntegerField(default=0, help_text='Session time in seconds')),
                ('c2_token', models.CharField(blank=True, help_text='Authentication token for Roblox bot websocket connection', max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BotConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_enabled', models.BooleanField(default=False)),
                ('sniper_enabled', models.BooleanField(default=False)),
                ('active_areas', models.JSONField(blank=True, default=list, help_text='List of active area IDs')),
                ('target_enchant_sets', models.JSONField(blank=True, default=list, help_text='Target sets of enchants (wishlist)')),
                ('whitelisted_uuids', models.JSONField(blank=True, default=list, help_text='Protected sword UUIDs/names')),
                ('webhook_url', models.URLField(blank=True, max_length=500)),
                ('webhook_enabled', models.BooleanField(default=False)),
                ('bot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='dashboard.botaccount')),
            ],
        ),
        migrations.CreateModel(
            name='TelemetryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(help_text='e.g. drop, snipe, teleport', max_length=50)),
                ('message', models.TextField()),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='dashboard.botaccount')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
