# Generated by Django 5.2.12 on 2026-05-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botaccount',
            name='backpack_items',
            field=models.JSONField(blank=True, default=list, help_text='Roblox in-game inventory backpack items'),
        ),
        migrations.AddField(
            model_name='botaccount',
            name='bot_class',
            field=models.CharField(default='Unbeatable', help_text='Ascender Class', max_length=100),
        ),
        migrations.AddField(
            model_name='botaccount',
            name='mold',
            field=models.CharField(default='Crystal', help_text='Ascender Mold', max_length=100),
        ),
        migrations.AddField(
            model_name='botaccount',
            name='quality',
            field=models.CharField(default='Spectacular', help_text='Ascender Quality', max_length=100),
        ),
        migrations.AddField(
            model_name='botaccount',
            name='rarity',
            field=models.CharField(default='Heavenly++', help_text='Ascender Rarity', max_length=100),
        ),
    ]
