# Generated by Django 5.2.12 on 2026-05-23 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_botaccount_backpack_items_botaccount_bot_class_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botconfiguration',
            old_name='sniper_enabled',
            new_name='snipe_enabled',
        ),
    ]
