# Generated by Django 5.2.12 on 2026-05-23 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_sniper_enabled_botconfiguration_snipe_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='botaccount',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Discord user owner', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bots', to=settings.AUTH_USER_MODEL),
        ),
    ]
