# Generated by Django 5.0.14 on 2026-05-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_botaccount_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalMetadata',
            fields=[
                ('key', models.CharField(default='game_data', max_length=50, primary_key=True, serialize=False)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Stores the JSON payload containing Areas, Enchants, Molds, etc.')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='botaccount',
            name='money',
            field=models.FloatField(default=0.0, help_text='Supports up to 10^308 for massive simulator values'),
        ),
    ]
