# Generated by Django 5.0.14 on 2026-05-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_globalmetadata_alter_botaccount_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='botaccount',
            name='ascender_enchant1',
            field=models.CharField(default='None', help_text='Ascender Enchant 1', max_length=100),
        ),
        migrations.AddField(
            model_name='botaccount',
            name='ascender_enchant2',
            field=models.CharField(default='None', help_text='Ascender Enchant 2', max_length=100),
        ),
        migrations.AddField(
            model_name='botaccount',
            name='ascender_enchant3',
            field=models.CharField(default='None', help_text='Ascender Enchant 3', max_length=100),
        ),
        migrations.AddField(
            model_name='botaccount',
            name='ascender_mode',
            field=models.CharField(default='None', help_text='Ascender Mode', max_length=100),
        ),
    ]
