# Generated by Django 5.0.14 on 2026-05-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_botaccount_ascender_enchant1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconfiguration',
            name='target_priority',
            field=models.CharField(default='Closest', max_length=50),
        ),
    ]
