# Generated by Django 5.2.12 on 2026-05-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_botconfiguration_target_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconfiguration',
            name='activate_panel',
            field=models.BooleanField(default=False),
        ),
    ]
