# Generated by Django 5.0.14 on 2026-05-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_botconfiguration_activate_panel'),
    ]

    operations = [
        migrations.AddField(
            model_name='botaccount',
            name='bank_level',
            field=models.IntegerField(default=0, help_text='Ascension bank capacity level'),
        ),
        migrations.AddField(
            model_name='botconfiguration',
            name='ascender_criteria',
            field=models.JSONField(blank=True, default=list, help_text='Criteria logic for ascension selection'),
        ),
        migrations.AddField(
            model_name='botconfiguration',
            name='ascender_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='botconfiguration',
            name='ascender_queue',
            field=models.JSONField(blank=True, default=list, help_text='Queue of UUIDs/names to upgrade'),
        ),
    ]
