# Generated by Django 5.0.14 on 2026-05-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_botaccount_bank_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botaccount',
            name='ascender_level',
            field=models.IntegerField(default=1, help_text='Ascender Sword Level'),
        ),
    ]
