# Generated by Django 5.0.14 on 2026-06-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_botaccount_ascender_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconfiguration',
            name='offset_height',
            field=models.IntegerField(default=7, help_text='Hover height when attacking NPCs'),
        ),
        migrations.AddField(
            model_name='botconfiguration',
            name='wait_altitude',
            field=models.IntegerField(default=15, help_text='Idle height when waiting for NPCs'),
        ),
    ]
