# Generated by Django 5.0.14 on 2026-06-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_botconfiguration_offset_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botaccount',
            name='status',
            field=models.CharField(default='Offline', max_length=100),
        ),
    ]
